export {Component as MimetypeAudioIcon} from "./MimetypeAudio.stories";
export {Component as MimetypeExcelIcon} from "./MimetypeExcel.stories";
export {Component as MimetypeImageIcon} from "./MimetypeImage.stories";
export {Component as MimetypePdfIcon} from "./MimetypePdf.stories";
export {Component as MimetypePresentationIcon} from "./MimetypePresentation.stories";
export {Component as MimetypeVideoIcon} from "./MimetypeVideo.stories";
export {Component as MimetypeWordIcon} from "./MimetypeWord.stories";
export {Component as MimetypeZipIcon} from "./MimetypeZip.stories";
export {Component as MimetypeOtherIcon} from "./MimetypeOther.stories";