import OutlinedCustomization from "./OutlinedCustomization.stories";
import OutlinedArrowDown from "./OutlinedArrowDown.stories";
import OutlinedMore from "./OutlinedMore.stories";
import Close from "@/stories/Icons/Close.stories";
import Separator from "@/stories/Icons/Separator.stories";
import HelpOutline from "@/stories/Icons/HelpOutline.stories";
import Back from "@/stories/Icons/Back.stories";
import Refresh from "@/stories/Icons/Refresh.stories";
import Home from "@/stories/Icons/Home.stories";
import MyWallet from "@/stories/Icons/MyWallet.stories";
import MyCart from "@/stories/Icons/MyCart.stories";
import Notifications from "@/stories/Icons/Notifications.stories";
import User from "@/stories/Icons/User.stories";
import Dashboard from "@/stories/Icons/Dashboard.stories";
import Logout from "@/stories/Icons/Logout.stories";
import HamburgerMenu from "@/stories/Icons/HamburgerMenu.stories";
import BackHistory from "@/stories/Icons/BackHistory.stories";
import HomeNavigation from "@/stories/Icons/HomeNavigation.stories";
import CartNavigation from "@/stories/Icons/CartNavigation.stories";
import Alarm from "@/stories/Icons/Alarm.stories";
import StarRate from "@/stories/Icons/StarRate.stories";
import OutlinedPack from "@/stories/Icons/OutlinedPack.stories";
import OutlinedAward from "@/stories/Icons/OutlinedAward.stories";
import OutlinedGift from "@/stories/Icons/OutlinedGift.stories";
import OutlinedWallet from "@/stories/Icons/OutlinedWallet.stories";
import OutlinedUser from "@/stories/Icons/OutlinedUser.stories";
import OutlinedSetting from "@/stories/Icons/OutlinedSetting.stories";




export const OutlinedCustomizationIcon = OutlinedCustomization.component;
export const OutlinedArrowDownIcon = OutlinedArrowDown.component;
export const OutlinedMoreIcon = OutlinedMore.component;
export const CloseIcon = Close.component;
export const SeparatorIcon = Separator.component;
export const HelpOutlineIcon = HelpOutline.component;
export const BackIcon = Back.component;
export const RefreshIcon = Refresh.component;
export const HomeIcon = Home.component;
export const MyWalletIcon = MyWallet.component;
export const MyCartIcon = MyCart.component;
export const NotificationsIcon = Notifications.component;
export const UserIcon = User.component;
export const DashboardIcon = Dashboard.component;
export const LogoutIcon = Logout.component;
export const HamburgerMenuIcon = HamburgerMenu.component;
export const BackHistoryIcon = BackHistory.component;
export const HomeNavigationIcon = HomeNavigation.component;
export const CartNavigationIcon = CartNavigation.component;
export const AlarmIcon = Alarm.component;
export const StarRateIcon = StarRate.component;
export const OutlinedPackIcon = OutlinedPack.component;
export const OutlinedAwardIcon = OutlinedAward.component;
export const OutlinedGiftIcon = OutlinedGift.component;
export const OutlinedWalletIcon = OutlinedWallet.component;
export const OutlinedUserIcon = OutlinedUser.component;
export const OutlinedSettingIcon = OutlinedSetting.component;
