name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.rahsazmashin.com

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rahsaz-app:latest

    - name: Tag the image
      run: docker tag rahsaz-app:latest registry.rahsazmashin.com/rahsaz-app:latest

    - name: Push the image to Docker Hub
      run: docker push registry.rahsazmashin.com/rahsaz-app:latest
