name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 hours

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure Docker daemon for insecure registry
      run: |
        echo '{"insecure-registries":["93.115.149.59:5000"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: 93.115.149.59:5000

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rahsaz-app:latest

    - name: Tag the image
      run: docker tag rahsaz-app:latest 93.115.149.59:5000/rahsaz-app:latest

    - name: Push the image to Docker Hub
      run:  |
        retry() {
          local retries=$1
          shift
          local count=0
          until "$@"; do
            exit=$?
            wait=$((2 ** count))
            count=$((count + 1))
            if [ $count -lt $retries ]; then
              echo "Retry $count/$retries failed, waiting $wait seconds..."
              sleep $wait
            else
              echo "Retry $count/$retries failed, no more retries left."
              return $exit
            fi
          done
          return 0
        }
        retry 3 docker push 93.115.149.59:5000/rahsaz-app:latest
